### PR TITLE
Create GCD_LCM.java

### PR DESCRIPTION
**Pull request by surya-prakash-susarla**
I have written this code to find out both the LCM and the GCD of any given numbers.

### CODE REVIEW

**Comment by vipin14119** [comment]
### Thanks for the contribution
little advice for you
1. Check out the Eular's algo for GCD
2. Your code is iterative  and is bit unclear for others , so try to make seperate functions for functionality

👍

**Comment by vipin14119** [comment]
## DO Check my other repository for making contributions 

I am currently working on these, check them out and spread the word if you like it

1. https://github.com/thebrokenloop/terminalJs
2. https://github.com/vipin14119/Qadapter

**Comment by surya-prakash-susarla** [comment]
Yeah i'll spread the word . Let me know if you are into any other projects.

**Comment by vipin14119** [comment]
check out my other repositories and my organisation **thebrokenloop** on GitHub

**Pull request merged**
